"""The Python/TypeScript seam, failing in both directions.

`apps/web/lib/items/projections.fixture.json` is generated by Python through the
real `visible_projection` and consumed by the Vitest renderer tests. That is what
makes the seam a contract rather than an intention:

* a renderer reading a field the projection does not carry fails **on the
  TypeScript side**, in `components/items/presentation/renders.test.tsx`;
* a projection change that is not re-exported fails **here**;
* and a fixture that has drifted from what the route actually serves fails here
  too — which is the assertion that stops this file describing a function while
  the wire describes something else.

That last one is W5a's lesson applied before it costs anything: **the thing that
verifies must measure the thing it reports on.** A fixture regenerated from the
same function it is checked against would agree with itself forever.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
EXPORTER = REPO_ROOT / "scripts" / "export_item_projections.py"
FIXTURE = REPO_ROOT / "apps" / "web" / "lib" / "items" / "projections.fixture.json"


def test_the_exporter_and_the_fixture_both_exist() -> None:
    """A guard for the checks below: a missing file passes an empty comparison."""
    assert EXPORTER.is_file()
    assert FIXTURE.is_file()


def test_the_committed_projections_are_current() -> None:
    """Regenerate in memory and compare. **Not a note in a README.**

    Run through the exporter's own `--check`, in a subprocess, so what is
    verified is the command a human would run rather than a reimplementation of
    it that could drift from the command.
    """
    result = subprocess.run(
        [sys.executable, str(EXPORTER), "--check"],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    assert result.returncode == 0, (
        "apps/web/lib/items/projections.fixture.json is stale — the renderer "
        "tests are checking a projection that no longer exists. Re-run:\n"
        "  python scripts/export_item_projections.py\n" + result.stderr
    )


def test_the_fixture_covers_every_type_exactly_once() -> None:
    from core.items import ITEM_TYPES, RESPONSE_MODE

    envelopes = json.loads(FIXTURE.read_text(encoding="utf-8"))
    types = [e["projection"]["item_type"] for e in envelopes]
    assert sorted(types) == sorted(ITEM_TYPES)
    for envelope in envelopes:
        assert envelope["response_mode"] == RESPONSE_MODE[
            envelope["projection"]["item_type"]
        ]


def test_the_fixture_carries_no_answer() -> None:
    """The renderer tests must not be able to read an answer either.

    If the committed file leaked one, a renderer could show it and every test on
    both sides would still pass — the same failure `visible_projection` exists
    to prevent, moved into a build artefact.
    """
    from core.items.projection import NEVER_VISIBLE

    for envelope in json.loads(FIXTURE.read_text(encoding="utf-8")):
        leaked = NEVER_VISIBLE & set(envelope["projection"])
        assert leaked == set(), (
            f"{envelope['projection']['item_type']} projects {sorted(leaked)}"
        )


# **The "does the fixture match the wire" assertion lives in
# `tests/test_items_route.py`**, next to the ASGI fixtures, and not here.
#
# It was written here first, comparing the committed file against
# `visible_projection` — the very function the file is generated from. That test
# passed and proved nothing: a fixture checked against its own source agrees
# with itself forever, whatever the route is actually serving. It is the same
# shape as the W5a harness that sampled twice and reported once, and it was
# caught for the same reason that one was: asking what the assertion measures.
