"""PRD §7.5's subtitle ladder: the five steps and the rules that move a learner.

**Pure: no SQL, no HTTP, no model, no I/O** — the same standing `score.py`,
`watch.py` and `cues.py` have, so the arithmetic is arguable without Postgres
and `core/video/` stays inside the model ban.

────────────────────────────────────────────────────────────────────────────────
THE FIVE STEPS, VERBATIM FROM PRD §7.5

    1  English + L1 subtitles (generated by us -- §2.5)  meaning, no anxiety
    2  English subtitles only                            sound -> written word
    3  English subtitles hidden -- tap any line          forces listening first
    4  No subtitles; reveal when lost, reveals counted   tolerating not-knowing
    5  No subtitles at all                               the goal

**THIS MODULE OWNS THE STEP AS A NUMBER AND NOTHING ELSE.** What each step
RENDERS is a surface question, and W13a ships no surface -- see the module
docstring of `core/services/subtitle_ladder.py` for which rungs are unbuildable
today and why. Keeping the number here and the rendering nowhere is deliberate:
a step is durable state, and a renderer that could only draw two of five rungs
would have had to guess at the other three.

────────────────────────────────────────────────────────────────────────────────
THE THREE BANDS, AND THE ASYMMETRY IS THE PRODUCT DECISION

PRD §7.5: *"Two comprehension checks at >=85% -> move up, announced. Below 60%
-> move down, silently (the v2 rule: raises announced, drops silent)."*

    score >= 85   a pass; the second pass at a step promotes, ANNOUNCED
    60 <= s < 85  nothing happens, and nothing is said
    score < 60    demote one step, SILENTLY, and clear the pass counter

**`announce` IS FALSE ON EVERY DEMOTION AND THAT IS LOAD-BEARING, NOT A
DEFAULT.** A "you have moved down to step 3" message is a guilt message with no
banned word in it -- CLAUDE.md §4 -- and **#348 is that exact mistake already
shipping in this product**, weekly, in the v2 Sunday report. The flag is
returned rather than left to the caller so no surface has to remember.

────────────────────────────────────────────────────────────────────────────────
TWO RULINGS PRD §7.5 DOES NOT MAKE, MADE HERE AND RECORDED

**(1) THE TWO PASSES ACCUMULATE; A MIDDLING CHECK DOES NOT RESET THEM.** 85 then
70 then 85 promotes. The declined alternative is strict consecutiveness. It is
refused because 70% is **not a failure by this ladder's own bands** -- below 60
is -- and making a non-failing score undo earned progress is a punishment for a
result the product otherwise treats as a non-event.

**(2) A FAILING CHECK CLEARS THE COUNTER EVEN WHEN IT CANNOT DEMOTE.** At step 1
there is nothing gentler to drop to, so the movement is `None`; the counter still
clears, because leaving a learner one check away from re-promoting to the step
they just failed out of is the same defect one rung down.

**AND ONE THING THAT IS NOT ACCUMULATED: passes at step 5.** There is nothing
above it. A counter climbing toward a promotion that cannot happen is a number
that means nothing, and it would break migration 022's `BETWEEN 0 AND 1`.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

#: PRD §7.5's five rungs.
STEPS: tuple[int, ...] = (1, 2, 3, 4, 5)
FIRST_STEP = STEPS[0]
TOP_STEP = STEPS[-1]

#: *"Two comprehension checks at >=85% -> move up."*
PROMOTE_PCT = 85
PASSES_TO_PROMOTE = 2

#: *"Below 60% -> move down."* Sixty exactly is NOT below sixty.
DEMOTE_PCT = 60

#: *"Two ladders: `youtube_curated` and `native_series`."* **Mirrored by
#: migration 022's CHECK, and `tests/test_migration_022.py` compares the two** --
#: one producer, never two hand-kept copies (#132's family).
#:
#: **`native_series` HAS NO PRODUCER TODAY** and cannot move: the series import
#: path (Language Reactor / Trancy, #172-#174) does not exist, so every `videos`
#: row is a YouTube one. The key exists anyway because PRD §7.5's whole point is
#: that the two skills are separate -- *"you will reach step 5 on BBC Learning
#: English long before you reach it on How I Met Your Mother"* -- and adding the
#: key later would be a migration this row exists to take now.
TRACK_KINDS: tuple[str, ...] = ("youtube_curated", "native_series")

Direction = Literal["up", "down"]


@dataclass(frozen=True, slots=True)
class LadderState:
    """Where a learner is on one ladder. **The default IS step 1 with no passes**,
    and a learner with no stored row is exactly that -- see
    `core.services.subtitle_ladder.ladder_for`, which does not write on a read.

    `passes_at_step` is 0 or 1 and never 2: the second pass promotes and resets
    it in the same movement. Migration 022 carries the same bound as a CHECK, so
    the invariant holds against a hand `UPDATE` as well as against this code.
    """

    step: int
    passes_at_step: int

    def __post_init__(self) -> None:
        if self.step not in STEPS:
            raise ValueError(f"step must be one of {STEPS}, got {self.step!r}")
        if not 0 <= self.passes_at_step < PASSES_TO_PROMOTE:
            raise ValueError(
                "passes_at_step must be in "
                f"0..{PASSES_TO_PROMOTE - 1}, got {self.passes_at_step!r}"
            )


@dataclass(frozen=True, slots=True)
class Movement:
    """What one comprehension check did.

    `direction` is `None` when nothing moved -- including a failing check at the
    floor, which is a real event that produced no movement. **`announce` is true
    only for `"up"`**, and `test_only_an_upward_movement_is_ever_announced`
    holds that across every step, counter and band rather than at one point.
    """

    state: LadderState
    direction: Direction | None
    announce: bool


def apply_check(state: LadderState, score_pct: int) -> Movement:
    """Apply one comprehension check to one ladder.

    **A score outside 0..100 is refused rather than clamped.** A percentage that
    is not one is a bug upstream, and clamping would let it through wearing a
    plausible number -- the shape #201 describes.
    """
    if not 0 <= score_pct <= 100:
        raise ValueError(f"score_pct must be 0..100, got {score_pct!r}")

    if score_pct < DEMOTE_PCT:
        # Silent, always. The counter clears whether or not the step moves.
        if state.step == FIRST_STEP:
            return Movement(
                LadderState(FIRST_STEP, 0), direction=None, announce=False
            )
        return Movement(
            LadderState(state.step - 1, 0), direction="down", announce=False
        )

    if score_pct >= PROMOTE_PCT:
        if state.step == TOP_STEP:
            return Movement(
                LadderState(TOP_STEP, 0), direction=None, announce=False
            )
        earned = state.passes_at_step + 1
        if earned >= PASSES_TO_PROMOTE:
            return Movement(
                LadderState(state.step + 1, 0), direction="up", announce=True
            )
        return Movement(
            LadderState(state.step, earned), direction=None, announce=False
        )

    # 60 <= score < 85: a real result that moves nothing and says nothing.
    return Movement(state, direction=None, announce=False)
