#!/usr/bin/env python3
"""Generate `data/lexemes.tsv` and `data/inflections.tsv` from the raw sources.

**Development-only. This never runs on the server.** It needs `lemminflect` and
`openpyxl`, pinned in `scripts/requirements-lexicon-build.txt`:

    .venv/bin/pip install -r scripts/requirements-lexicon-build.txt

and then, with the two raw inputs downloaded (see `data/LICENCES.md` for the
URLs and the checksums this expects):

    .venv/bin/python scripts/build_lexicon.py \
        --frequency  <dir>/en_full.txt \
        --cefrj      "<dir>/CEFR-J Wordlist Ver1.6.xlsx"

Why the generated tables are committed rather than produced at deploy time:
`packages/core/lexicon/normalize.py` must lemmatise identically in the seed
builder, in every ledger write and in every coverage computation, forever. A
committed table is byte-identical across versions and inspectable in a diff; a
statistical model is neither, and it would add a download step to a deployment
sequence that is settled (CLAUDE.md §5).

The raw inputs are deliberately **not** committed — only this script, the
pinned URLs and the checksums in `data/LICENCES.md`. That is what keeps
`data/lexemes.tsv` re-derivable and therefore deletable: removing it is a
delete plus a re-run of this script, not a re-architecture.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "data"

# A plausible English surface form. Lowercase letters, with internal apostrophes
# and hyphens allowed. Everything else in the OpenSubtitles list — digits,
# markup residue, other scripts — is not vocabulary.
SURFACE = re.compile(r"^[a-z](?:[a-z'-]*[a-z])?$")
# Single letters are almost all OCR noise. `a` and `i` are the two real words.
REAL_SINGLE_LETTERS = frozenset({"a", "i"})

# How far down the surface list to look. At surface rank 80,000 the corpus
# count is around 60, which is already deep into proper nouns; going further
# adds noise, not vocabulary.
SURFACE_LIMIT = 80_000
LEMMA_TARGET = 15_000
BAND_SIZE = 1_000

# Used to pick one part of speech when a surface is its own lemma under several.
POS_PRIORITY = (
    "NOUN", "VERB", "ADJ", "ADV", "PROPN", "AUX", "PRON",
    "DET", "ADP", "NUM", "PART", "INTJ", "CCONJ", "SCONJ",
)

# CEFR-J's `pos` column, mapped to the coarse UPOS tags lemminflect uses, so
# `lexemes.pos` means one thing regardless of which source supplied it.
CEFRJ_POS = {
    "noun": "NOUN", "verb": "VERB", "adjective": "ADJ", "adverb": "ADV",
    "preposition": "ADP", "pronoun": "PRON", "determiner": "DET",
    "conjunction": "CCONJ", "interjection": "INTJ", "number": "NUM",
    "auxiliary verb": "AUX", "modal verb": "AUX", "infinitive marker": "PART",
}
CEFR_ORDER = ("A1", "A2", "B1", "B2", "C1", "C2")

ATTRIBUTION = """\
# Generated by scripts/build_lexicon.py — do not edit by hand.
#
# This file is licensed CC BY-SA 4.0. It is a derivative of two sources:
#
#   Frequency ranks and bands
#     FrequencyWords (OpenSubtitles-derived), Hermit Dave.
#     https://github.com/hermitdave/FrequencyWords
#     The repository's README declares "MIT License for code. CC-by-sa-4.0 for
#     content." The word lists are content, so this file inherits CC BY-SA 4.0.
#
#   CEFR level tags
#     The CEFR-J Wordlist Version 1.6. Compiled by Yukio Tono, Tokyo University
#     of Foreign Studies. Retrieved from http://www.cefr-j.org/download_eng
#     on 2026-08-24. Copyright Tono Laboratory, TUFS. Used with acknowledgement.
#
# Full terms, verbatim quotes and the raw-input checksums: data/LICENCES.md
"""


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def read_frequency(path: Path) -> list[tuple[str, int]]:
    """The `surface count` list, filtered and truncated, still rank-ordered."""
    kept: list[tuple[str, int]] = []
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            parts = line.split()
            if len(parts) != 2:
                continue
            surface, raw_count = parts
            if len(surface) > 64 or not SURFACE.match(surface):
                continue
            if len(surface) == 1 and surface not in REAL_SINGLE_LETTERS:
                continue
            kept.append((surface, int(raw_count)))
            if len(kept) >= SURFACE_LIMIT:
                break
    return kept


def read_cefrj(path: Path) -> dict[str, tuple[str, str | None]]:
    """headword -> (easiest CEFR level, coarse POS at that level).

    A headword listed at several levels under different parts of speech takes
    the **easiest** one: a word first met at A1 in any reading is an A1 word to
    a learner, and taking the hardest would systematically overstate the
    difficulty of the commonest vocabulary.
    """
    import openpyxl

    workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
    sheet = workbook["ALL_sep"]
    best: dict[str, tuple[str, str | None]] = {}
    for row in sheet.iter_rows(min_row=2, values_only=True):
        if not row or not row[0]:
            continue
        headword = str(row[0]).strip().lower()
        pos = CEFRJ_POS.get(str(row[1] or "").strip().lower())
        level = str(row[2] or "").strip().upper()
        if level not in CEFR_ORDER or not SURFACE.match(headword):
            continue
        current = best.get(headword)
        if current is None or CEFR_ORDER.index(level) < CEFR_ORDER.index(current[0]):
            best[headword] = (level, pos)
    workbook.close()
    return best


def resolve_lemma(
    surface: str, counts: dict[str, int]
) -> tuple[str, tuple[str, ...]]:
    """Map one surface form to its lemma, and to the tags it can carry.

    The candidate with the **highest corpus count** wins, with length and
    alphabetical order as deterministic tie-breaks. A surface that is its own
    lemma keeps itself only when nothing more frequent claims it.

    Deciding by corpus evidence rather than by a fixed part-of-speech order is
    what makes this behave. lemminflect offers a base-form reading for almost
    every `-ing` and `-ed` word — `running` is a NOUN lemma as well as a form of
    `run` — so a rule that let the surface win outright would give `run` and
    `running` separate ledger entries, which is precisely the fragmentation the
    lemma key exists to prevent. Counts settle it the way usage does: `run`
    outweighs `running`, so `running` folds in; `building` outweighs `build` as
    people actually speak, so it keeps its own entry, which is right — a
    building is a different word from building something.
    """
    from lemminflect import getAllLemmas

    by_lemma: dict[str, set[str]] = defaultdict(set)
    for upos, lemmas in getAllLemmas(surface).items():
        for lemma in lemmas:
            by_lemma[lemma].add(upos)
    if not by_lemma:
        return surface, ()
    chosen = max(
        sorted(by_lemma),
        key=lambda lemma: (counts.get(lemma, 0), -len(lemma)),
    )
    return chosen, tuple(sorted(by_lemma[chosen]))


def pick_pos(tags: tuple[str, ...], cefrj_pos: str | None) -> str:
    """One coarse POS per lemma. CEFR-J's reading wins when it is one of ours."""
    if cefrj_pos and cefrj_pos in tags:
        return cefrj_pos
    for candidate in POS_PRIORITY:
        if candidate in tags:
            return candidate
    return cefrj_pos or ""


def build_lexemes(
    frequency: list[tuple[str, int]], cefrj: dict[str, tuple[str, str | None]]
) -> tuple[list[dict], dict[str, tuple[str, ...]]]:
    counts = dict(frequency)
    totals: dict[str, int] = defaultdict(int)
    tags: dict[str, set[str]] = defaultdict(set)

    # Frequency is aggregated **per lemma**, not per surface form. The ledger
    # is keyed on lemmas, so `run` must not compete with `running` for a place
    # in the top-N band — between them they are one word.
    for surface, count in frequency:
        lemma, upos = resolve_lemma(surface, counts)
        totals[lemma] += count
        tags[lemma].update(upos)

    ranked = sorted(totals.items(), key=lambda kv: (-kv[1], kv[0]))[:LEMMA_TARGET]
    rows: list[dict] = []
    for index, (lemma, total) in enumerate(ranked, start=1):
        level, cefrj_pos = cefrj.get(lemma, (None, None))
        rows.append(
            {
                "lemma": lemma,
                "pos": pick_pos(tuple(sorted(tags[lemma])), cefrj_pos),
                "freq_rank": index,
                "freq_band": (index - 1) // BAND_SIZE + 1,
                "cefr": level or "",
                "count": total,
            }
        )
    return rows, {row["lemma"]: tuple(sorted(tags[row["lemma"]])) for row in rows}


def repair_silent_e(form: str, lemma: str) -> str:
    """`lemminflect` spells some `-e`-final comparatives by appending, not by
    dropping the `e`: `free` → `freeer`, `blue` → `blueest`.

    It gets `nice` → `nicer` and `true` → `truest` right, so the fault is
    per-lemma rather than systematic, which is why it produced only eleven bad
    rows across six lemmas and why nothing noticed. **A lemma ending in `e`
    always drops that `e` before `-er`/`-est`** — there is no exception in
    English — so this repair is safe to apply unconditionally.

    **Scoped to those two suffixes on purpose.** `-ed` and `-ing` are NOT
    touched: `being`, `ageing`, `queueing`, `bingeing` and `tieing` are all
    correct English, and the scan that found this bug listed them only because
    it was matching the *shape* `lemma + suffix`, not a fault. Widening this to
    them would move rows with no defect behind them. See **#282**.
    """
    if not lemma.endswith("e"):
        return form
    for suffix in ("est", "er"):
        if form == lemma + suffix:
            return lemma[:-1] + suffix
    return form


def build_inflections(
    rows: list[dict], tags: dict[str, tuple[str, ...]]
) -> list[tuple[str, str]]:
    """Every surface form of every seeded lemma, mapped back to that lemma.

    Generated from the paradigm rather than harvested from the corpus, so a
    form the two learners happen never to have met is still resolvable.

    Homographs — `saw` is both a lemma of its own and the past tense of `see` —
    resolve to **the lemma with the better frequency rank**, with the surface's
    own entry given no privilege. Identity looks like the safe default and is
    not: `saw` earns a lexeme row at rank 10,415 off `sawing`/`sawed`, while
    `see` sits at rank 49, so privileging identity would leave "I saw a film"
    unresolvable for a learner who plainly knows `see`. Ranking by frequency
    picks the reading people actually use. The cost is that the rarer reading
    of a homograph is not separately reachable, which coverage does not need
    and W13 can revisit with a real word-sense step.
    """
    from lemminflect import getAllInflections

    rank = {row["lemma"]: row["freq_rank"] for row in rows}
    best: dict[str, str] = {}
    for row in rows:
        lemma = row["lemma"]
        forms: set[str] = set()
        # A lemma no surface form tagged — most function words, and anything
        # lemminflect declined to analyse — still gets its paradigm attempted
        # under the three open classes rather than being left with none.
        for upos in tags.get(lemma) or ("NOUN", "VERB", "ADJ"):
            for spellings in getAllInflections(lemma, upos=upos).values():
                forms.update(spellings)
        for spelling in forms:
            # Repaired BEFORE the filters below, so the corrected spelling is
            # what gets rank-compared and written (#282).
            form = repair_silent_e(spelling.lower(), lemma)
            if form == lemma or not SURFACE.match(form) or len(form) > 64:
                continue
            incumbent = best.get(form)
            if incumbent is None or rank[lemma] < rank[incumbent]:
                best[form] = lemma
    # A form that is itself a better-ranked lemma resolves to itself, so drop
    # any mapping the lemma table already answers more directly.
    return sorted(
        (form, lemma)
        for form, lemma in best.items()
        if form not in rank or rank[lemma] < rank[form]
    )


def write_tsv(path: Path, header: str, lines: list[str]) -> None:
    path.write_text(
        ATTRIBUTION + header + "\n" + "\n".join(lines) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--frequency", required=True, type=Path)
    parser.add_argument("--cefrj", required=True, type=Path)
    parser.add_argument("--out-dir", type=Path, default=DATA_DIR)
    args = parser.parse_args()

    for path in (args.frequency, args.cefrj):
        if not path.is_file():
            print(f"missing input: {path}", file=sys.stderr)
            return 2
        print(f"{path.name}\n  sha256 {sha256(path)}")

    frequency = read_frequency(args.frequency)
    cefrj = read_cefrj(args.cefrj)
    print(f"surfaces kept {len(frequency)}, CEFR-J headwords {len(cefrj)}")

    rows, tags = build_lexemes(frequency, cefrj)
    inflections = build_inflections(rows, tags)
    tagged = sum(1 for row in rows if row["cefr"])
    print(f"lexemes {len(rows)} ({tagged} with a CEFR tag), forms {len(inflections)}")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_tsv(
        args.out_dir / "lexemes.tsv",
        "lemma\tpos\tfreq_rank\tfreq_band\tcefr",
        [
            f"{r['lemma']}\t{r['pos']}\t{r['freq_rank']}\t{r['freq_band']}\t{r['cefr']}"
            for r in rows
        ],
    )
    write_tsv(
        args.out_dir / "inflections.tsv",
        "surface\tlemma",
        [f"{surface}\t{lemma}" for surface, lemma in inflections],
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
