import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import fixtures from "@/lib/items/projections.fixture.json";

import { PRESENTED_TYPES, presentationFor } from "./index";

/**
 * Every one of the eleven types renders from the projection a learner actually
 * receives. **This is the half of the contract that fails on the TypeScript
 * side**: `projections.fixture.json` is generated by Python through the real
 * `visible_projection`, so a renderer reaching for a field the projection does
 * not carry fails here, and a projection change that breaks a renderer fails in
 * `tests/test_items_web_contract.py` on the other side.
 *
 * The eleven are named as literals on purpose. A loop over the fixture alone
 * would pass with three types in the file, and
 * `tests/test_web_shell.py::test_every_item_type_has_a_render_test` reads
 * `core.items.ITEM_TYPES` out of Python and requires each one to appear in a
 * test here — so a twelfth type fails the suite until somebody renders it,
 * which a file count could never do.
 */
const TYPES = [
  "mcq",
  "cloze_cued",
  "word_bank_order",
  "error_spot",
  "l1_to_l2_production",
  "dictation",
  "listening_gap",
  "speak_repeat",
  "speak_answer",
  "match_pairs",
  "collocation_pick",
] as const;

type Envelope = {
  id: number;
  response_mode: string;
  projection: Record<string, unknown>;
};

const BY_TYPE = new Map(
  (fixtures as Envelope[]).map((e) => [e.projection["item_type"] as string, e]),
);

describe("the eleven presentation components", () => {
  it("covers exactly the types the committed projections carry", () => {
    // Neither side is allowed to drift quietly: the literal list above, the map
    // in index.ts, and the generated fixture must name the same eleven.
    expect([...TYPES].sort()).toEqual([...BY_TYPE.keys()].sort());
    expect([...TYPES].sort()).toEqual([...PRESENTED_TYPES].sort());
  });

  it.each(TYPES)("renders %s from its committed projection", (itemType) => {
    const envelope = BY_TYPE.get(itemType);
    expect(envelope, `no fixture for ${itemType}`).toBeDefined();
    const Presentation = presentationFor(itemType);
    expect(Presentation, `no component for ${itemType}`).not.toBeNull();
    if (!Presentation || !envelope) return;

    const { container } = render(
      <Presentation
        itemId={envelope.id}
        projection={envelope.projection}
        draft={{}}
        onDraft={() => {}}
        disabled={false}
      />,
    );

    // A missing field surfaces as the literal string "undefined" in the DOM far
    // more often than as a crash, and it looks like content to a reader.
    expect(container.textContent ?? "").not.toContain("undefined");
    expect(container.textContent?.trim().length ?? 0).toBeGreaterThan(0);
  });

  it("shows the applied cue when the projection carries one", () => {
    const envelope = BY_TYPE.get("cloze_cued")!;
    const Presentation = presentationFor("cloze_cued")!;
    render(
      <Presentation
        itemId={envelope.id}
        projection={envelope.projection}
        draft={{}}
        onDraft={() => {}}
        disabled={false}
      />,
    );
    expect(screen.getByTestId("item-cue")).toHaveTextContent("(past of go)");
  });

  it("renders nothing for a type it has never heard of", () => {
    // A twelfth type added in Python must not throw on a phone. The suite is
    // where that should fail, and the test above is what makes it.
    expect(presentationFor("time_travel")).toBeNull();
    expect(presentationFor(undefined)).toBeNull();
  });
});
